"""initial schema

Revision ID: 32ec7ead3c65
Revises:
Create Date: 2026-07-30 17:39:49.319693+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "32ec7ead3c65"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("environment_id", sa.String(length=64), nullable=False),
        sa.Column("adapter_version", sa.String(length=64), nullable=False),
        sa.Column("data_origin", sa.String(length=16), nullable=False),
        sa.Column("execution_mode", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("declaration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("declaration_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(data_origin, execution_mode) IN (('observed','replay'),('synthetic','replay'),('synthetic','simulation'),('observed','live'))",
            name=op.f("ck_campaigns_admissible_origin_mode"),
        ),
        sa.PrimaryKeyConstraint("campaign_id", name=op.f("pk_campaigns")),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("idempotency_key", name=op.f("pk_idempotency_keys")),
    )
    op.create_table(
        "record_relations",
        sa.Column("relation_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column("predicate", sa.String(length=32), nullable=False),
        sa.Column("object_id", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "predicate IN ('derived_from','supersedes','invalidates','replaces')",
            name=op.f("ck_record_relations_known_predicate"),
        ),
        sa.CheckConstraint(
            "subject_id <> object_id", name=op.f("ck_record_relations_no_self_relation")
        ),
        sa.PrimaryKeyConstraint("relation_id", name=op.f("pk_record_relations")),
        sa.UniqueConstraint(
            "subject_id", "predicate", "object_id", name="uq_record_relations_triple"
        ),
    )
    op.create_table(
        "storage_objects",
        sa.Column("object_uri", sa.Text(), nullable=False),
        sa.Column("bucket", sa.String(length=128), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state <> 'committed' OR (sha256 IS NOT NULL AND byte_size IS NOT NULL AND committed_at IS NOT NULL)",
            name=op.f("ck_storage_objects_committed_object_is_verified"),
        ),
        sa.CheckConstraint(
            "state IN ('pending','committed','orphaned')",
            name=op.f("ck_storage_objects_known_object_state"),
        ),
        sa.PrimaryKeyConstraint("object_uri", name=op.f("pk_storage_objects")),
    )
    op.create_table(
        "budget_ledger",
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("work_item_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('reserved','consumed','released')",
            name=op.f("ck_budget_ledger_known_ledger_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.campaign_id"],
            name=op.f("fk_budget_ledger_campaign_id_campaigns"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("entry_id", name=op.f("pk_budget_ledger")),
    )
    op.create_table(
        "events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("causation_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "schema_version >= 1", name=op.f("ck_events_schema_version_starts_at_one")
        ),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_events_sequence_starts_at_one")),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.campaign_id"],
            name=op.f("fk_events_campaign_id_campaigns"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_events")),
        sa.UniqueConstraint("aggregate_id", "sequence", name="uq_events_aggregate_sequence"),
    )
    op.create_index(
        "ix_events_replay", "events", ["campaign_id", "aggregate_id", "sequence"], unique=False
    )
    op.create_table(
        "work_items",
        sa.Column("work_item_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.String(length=128), nullable=False),
        sa.Column("candidate", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("quarantine_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state <> 'quarantined' OR quarantine_reason IS NOT NULL",
            name=op.f("ck_work_items_quarantine_states_its_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.campaign_id"],
            name=op.f("fk_work_items_campaign_id_campaigns"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("work_item_id", name=op.f("pk_work_items")),
        sa.UniqueConstraint("campaign_id", "candidate_id", name="uq_work_items_campaign_candidate"),
    )
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("work_item_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_token", sa.UUID(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("command_version", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("last_failure", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(lease_owner IS NULL) = (lease_expires_at IS NULL)",
            name=op.f("ck_jobs_lease_owner_and_expiry_together"),
        ),
        sa.CheckConstraint("attempt_count >= 0", name=op.f("ck_jobs_attempt_count_non_negative")),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.work_item_id"],
            name=op.f("fk_jobs_work_item_id_work_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idempotency_key", name="uq_jobs_idempotency_key"),
    )
    op.create_index(
        "ix_jobs_claimable",
        "jobs",
        ["available_at"],
        unique=False,
        postgresql_where=sa.text("state = 'available'"),
    )
    op.create_table(
        "attempts",
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("work_item_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ordinal >= 1", name=op.f("ck_attempts_ordinal_starts_at_one")),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.job_id"], name=op.f("fk_attempts_job_id_jobs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.work_item_id"],
            name=op.f("fk_attempts_work_item_id_work_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("attempt_id", name=op.f("pk_attempts")),
        sa.UniqueConstraint("work_item_id", "ordinal", name="uq_attempts_work_item_ordinal"),
    )
    op.create_table(
        "observations",
        sa.Column("observation_id", sa.String(length=128), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("work_item_id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("object_uri", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("signal_kind", sa.String(length=32), nullable=False),
        sa.Column("quantities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("data_origin", sa.String(length=16), nullable=False),
        sa.Column("execution_mode", sa.String(length=16), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(data_origin, execution_mode) IN (('observed','replay'),('synthetic','replay'),('synthetic','simulation'),('observed','live'))",
            name=op.f("ck_observations_admissible_origin_mode"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('corrupted','invalidated') OR status_reason IS NOT NULL",
            name=op.f("ck_observations_rejected_status_states_its_reason"),
        ),
        sa.CheckConstraint("byte_size >= 0", name=op.f("ck_observations_byte_size_non_negative")),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.attempt_id"],
            name=op.f("fk_observations_attempt_id_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.campaign_id"],
            name=op.f("fk_observations_campaign_id_campaigns"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.work_item_id"],
            name=op.f("fk_observations_work_item_id_work_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("observation_id", name=op.f("pk_observations")),
    )
    op.create_table(
        "attempt_outcomes",
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("work_item_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("observation_id", sa.String(length=128), nullable=True),
        sa.Column("failure", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "cost",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "observation_id IS NULL OR status IN ('succeeded','corrupted')",
            name=op.f("ck_attempt_outcomes_observation_only_when_bytes_arrived"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('failed_retryable','failed_terminal') OR failure IS NOT NULL",
            name=op.f("ck_attempt_outcomes_failed_status_carries_a_failure"),
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.attempt_id"],
            name=op.f("fk_attempt_outcomes_attempt_id_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.observation_id"],
            name=op.f("fk_attempt_outcomes_observation_id_observations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.work_item_id"],
            name=op.f("fk_attempt_outcomes_work_item_id_work_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("attempt_id", name=op.f("pk_attempt_outcomes")),
    )
    op.create_index(
        "uq_attempt_outcomes_one_success_per_work_item",
        "attempt_outcomes",
        ["work_item_id"],
        unique=True,
        postgresql_where=sa.text("status = 'succeeded'"),
    )
    op.create_table(
        "derived_metrics",
        sa.Column("metric_id", sa.String(length=128), nullable=False),
        sa.Column("observation_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("value_numeric", sa.Numeric(), nullable=True),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("uncertainty", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("analysis_name", sa.String(length=128), nullable=False),
        sa.Column("analysis_version", sa.String(length=32), nullable=False),
        sa.Column("parameter_hash", sa.String(length=64), nullable=False),
        sa.Column("quality_status", sa.String(length=16), nullable=False),
        sa.Column("quality_reason", sa.Text(), nullable=True),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "quality_status = 'accepted' OR quality_reason IS NOT NULL",
            name=op.f("ck_derived_metrics_non_accepted_metric_states_its_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.observation_id"],
            name=op.f("fk_derived_metrics_observation_id_observations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("metric_id", name=op.f("pk_derived_metrics")),
        sa.UniqueConstraint(
            "observation_id",
            "name",
            "analysis_name",
            "analysis_version",
            "parameter_hash",
            name="uq_derived_metrics_analysis",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("derived_metrics")
    op.drop_index(
        "uq_attempt_outcomes_one_success_per_work_item",
        table_name="attempt_outcomes",
        postgresql_where=sa.text("status = 'succeeded'"),
    )
    op.drop_table("attempt_outcomes")
    op.drop_table("observations")
    op.drop_table("attempts")
    op.drop_index(
        "ix_jobs_claimable", table_name="jobs", postgresql_where=sa.text("state = 'available'")
    )
    op.drop_table("jobs")
    op.drop_table("work_items")
    op.drop_index("ix_events_replay", table_name="events")
    op.drop_table("events")
    op.drop_table("budget_ledger")
    op.drop_table("storage_objects")
    op.drop_table("record_relations")
    op.drop_table("idempotency_keys")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
