"""carry the normalisation basis on a derived metric

`A/cm^2` states the dimension; it does not say *which* cm² — geometric, meniscus contact, or ECSA —
and the archive states none of them. The caveat previously lived only on an in-memory dataclass, so
it reached neither the row nor the exported bundle: a caveat that does not reach the export is not a
caveat. Encoding it into the unit string instead would break every unit comparison and change the
identity hash for a non-dimensional reason, so it rides its own nullable column.

Nullable and un-backfilled on purpose: existing rows were written by an analysis that did not record
a basis, and writing `unknown` into them would assert that the old analysis made a determination it
never made.

Revision ID: 1e6a158aabea
Revises: b082c5c8f0f1
Create Date: 2026-07-31 18:01:56.579244+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1e6a158aabea"
down_revision: str | None = "b082c5c8f0f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "derived_metrics", sa.Column("normalisation_basis", sa.String(length=32), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("derived_metrics", "normalisation_basis")
    # ### end Alembic commands ###
