"""The HER replay adapter.

`docs/SPEC.md` §9.1: the adapter maps a typed location to an actual source record or to a structured
unavailable outcome. It never interpolates, never imputes, never substitutes a predicted property
for an observed one, and never presents a replay as a new measurement
(`docs/DATA_STRATEGY.md` §2.6).

**Origin comes from the evidence on disk, not from a flag.** ADR-010 makes `synthetic + replay` and
`observed + replay` both admissible, and the same adapter code serves both. Which one applies is
decided by what the landing root contains: a `fixture_manifest.json` means generated bytes, a
`provenance.json` means acquired bytes. A root holding both is ambiguous and fails, because guessing
here is precisely the origin conflation invariant 1 forbids.

The member grammar below was read from the recorded inventory
(`docs/specs/gate0-her-source-acquisition.md` §13), never from memory. A member that does not match
is *reported*, not silently skipped: an unrecognised archive layout is F-019, and coercing it would
hide a source change.
"""

from __future__ import annotations

import asyncio
import re
import zipfile
from dataclasses import dataclass, field
from decimal import Decimal
from pathlib import Path
from typing import ClassVar, Final, Literal

from labbridge.domain.candidates import HerCandidate
from labbridge.domain.identity import EnvironmentRef
from labbridge.domain.provenance import SourceRecord, SyntheticRoot
from labbridge.infrastructure.her_ingestion.fixture import FIXTURE_MANIFEST_FILENAME
from labbridge.infrastructure.her_ingestion.provenance import PROVENANCE_FILENAME
from labbridge.infrastructure.objectstore import digest

ENVIRONMENT_ID: Final = "her_auirrh"
#: Bumped when the member grammar or the emitted descriptors change, so a stored record always says
#: which adapter produced it.
ADAPTER_VERSION: Final = "1"
SEARCH_ARCHIVE: Final = "SECCM_dataset.zip"
MEDIA_TYPE: Final = "text/csv"
#: The schema this adapter knows how to emit. An archive whose LSV header differs is unsupported.
LSV_SCHEMA_VERSION: Final = "1"

#: From the recorded inventory. `library` is the rich-element label, `area` the grid identifier.
_LSV_MEMBER: Final = re.compile(
    r"^SECCM_dataset/Au-Ir-Rh_(?P<library>[A-Za-z]+-rich)_SECCM_area_(?P<area>\d+)"
    r"_x=(?P<x>-?\d+\.\d+)_y=(?P<y>-?\d+\.\d+)_LSV\.csv$"
)
_FIT_MEMBER: Final = "SECCM_dataset/LSV_fit_parameters.csv"

#: The LSV header the inventory recorded, in order. Used to reject an unrecognised schema loudly
#: rather than parsing whatever arrives (F-019).
EXPECTED_LSV_HEADER: Final = (
    "Potential vs. RHE [V]",
    "Current density [A/cm^2]",
    "Standard deviation [A/cm^2]",
)


class ReplayAdapterError(Exception):
    code: ClassVar[str] = "replay_adapter_error"


class AmbiguousRootError(ReplayAdapterError):
    """A root that looks both generated and acquired. Never resolved by preferring one."""

    code: ClassVar[str] = "ambiguous_source_root"


class UnknownRootError(ReplayAdapterError):
    """Neither marker present, so the origin of these bytes is unknown and cannot be recorded."""

    code: ClassVar[str] = "unknown_source_root"


class UnsupportedSchemaError(ReplayAdapterError):
    """F-019. Raw source is retained; ingestion stops until an adapter version is added."""

    code: ClassVar[str] = "unsupported_schema"

    def __init__(self, member: str, found: tuple[str, ...]) -> None:
        self.member = member
        self.found = found
        super().__init__(
            f"member `{member}` header {found} does not match adapter version "
            f"{ADAPTER_VERSION} (expected {EXPECTED_LSV_HEADER})"
        )


@dataclass(frozen=True)
class LocationKey:
    library_id: str
    measurement_area_id: str


@dataclass(frozen=True)
class SourceLocation:
    """One LSV member, located without reading it."""

    member_path: str
    grid_x: Decimal
    grid_y: Decimal


@dataclass(frozen=True)
class AdapterSuccess:
    kind: Literal["success"] = field(default="success", init=False)
    payload: bytes = b""
    media_type: str = MEDIA_TYPE
    schema_version: str = LSV_SCHEMA_VERSION
    signal_kind: Literal["lsv"] = "lsv"
    source_path: str = ""
    source_sha256: str = ""
    #: The coordinates the *filename* carries. Recorded rather than checked against the candidate:
    #: a disagreement is a scientific finding for a validation step, not a transport failure.
    recorded_grid_x: Decimal = Decimal(0)
    recorded_grid_y: Decimal = Decimal(0)


@dataclass(frozen=True)
class AdapterUnavailable:
    """F-017. The location was never measured. This is data, not an error to work around."""

    kind: Literal["unavailable"] = field(default="unavailable", init=False)
    failure_code: str = "source_location_unavailable"
    reason: str = ""


AdapterResult = AdapterSuccess | AdapterUnavailable


def resolve_environment(root: Path) -> tuple[EnvironmentRef, Path]:
    """Decide origin from what the root actually contains, and return the SECCM archive path."""
    has_fixture = (root / FIXTURE_MANIFEST_FILENAME).exists()
    has_provenance = (root / PROVENANCE_FILENAME).exists()
    if has_fixture and has_provenance:
        raise AmbiguousRootError(
            f"{root} holds both {FIXTURE_MANIFEST_FILENAME} and {PROVENANCE_FILENAME}; "
            "the origin of these bytes cannot be determined"
        )
    if not has_fixture and not has_provenance:
        raise UnknownRootError(
            f"{root} holds neither {FIXTURE_MANIFEST_FILENAME} nor {PROVENANCE_FILENAME}; "
            "run `labbridge fetch-her` or `labbridge build-her-fixture` first"
        )
    origin = "synthetic" if has_fixture else "observed"
    return (
        EnvironmentRef(
            environment_id=ENVIRONMENT_ID,
            adapter_version=ADAPTER_VERSION,
            data_origin=origin,
            execution_mode="replay",
        ),
        root / SEARCH_ARCHIVE,
    )


def build_index(archive: Path) -> tuple[dict[LocationKey, SourceLocation], tuple[str, ...]]:
    """Map every LSV member to its location, and report every member that did not match.

    Unmatched members are returned rather than dropped: the fit table and any future member type
    are legitimate, but an *unexpected* one is how a source layout change first shows itself.
    """
    index: dict[LocationKey, SourceLocation] = {}
    unmatched: list[str] = []
    with zipfile.ZipFile(archive) as zf:
        for info in zf.infolist():
            if info.is_dir():
                continue
            match = _LSV_MEMBER.match(info.filename)
            if match is None:
                if info.filename != _FIT_MEMBER:
                    unmatched.append(info.filename)
                continue
            key = LocationKey(
                library_id=match.group("library"), measurement_area_id=match.group("area")
            )
            index[key] = SourceLocation(
                member_path=info.filename,
                grid_x=Decimal(match.group("x")),
                grid_y=Decimal(match.group("y")),
            )
    return index, tuple(sorted(unmatched))


def _check_header(member: str, payload: bytes) -> None:
    """Reject an unrecognised schema loudly. Never coerce, never default, never guess (F-019)."""
    first, _, _ = (
        payload.decode("utf-8-sig", errors="replace")
        .replace("\r\n", "\n")
        .replace("\r", "\n")
        .partition("\n")
    )
    found = tuple(cell.strip() for cell in first.split(","))
    if found != EXPECTED_LSV_HEADER:
        raise UnsupportedSchemaError(member, found)


class HerReplayAdapter:
    """Returns the recorded observation for a location, or a structured unavailable outcome."""

    def __init__(self, root: Path) -> None:
        self.environment, self._archive = resolve_environment(root)
        self._root = root
        self._index, self.unmatched_members = build_index(self._archive)

    @property
    def location_count(self) -> int:
        return len(self._index)

    def known_locations(self) -> tuple[LocationKey, ...]:
        return tuple(sorted(self._index, key=lambda k: (k.library_id, int(k.measurement_area_id))))

    def validate_candidate(self, candidate: HerCandidate) -> AdapterResult | None:
        """`None` when the candidate names a location this archive holds.

        A candidate for a location with no LSV gets the same structured unavailable outcome
        `execute` would return, so a caller can reject early without a different code path.
        """
        key = LocationKey(candidate.library_id, candidate.measurement_area_id)
        if key in self._index:
            return None
        return AdapterUnavailable(
            reason=(
                f"library `{candidate.library_id}` area `{candidate.measurement_area_id}` has no "
                "recorded LSV in this source; the location was not measured"
            )
        )

    async def execute(self, candidate: HerCandidate) -> AdapterResult:
        """Read the recorded bytes for this location. Never fabricates a missing one."""
        unavailable = self.validate_candidate(candidate)
        if unavailable is not None:
            return unavailable

        key = LocationKey(candidate.library_id, candidate.measurement_area_id)
        location = self._index[key]
        payload = await asyncio.to_thread(self._read_member, location.member_path)
        _check_header(location.member_path, payload)
        return AdapterSuccess(
            payload=payload,
            source_path=location.member_path,
            source_sha256=digest(payload),
            recorded_grid_x=location.grid_x,
            recorded_grid_y=location.grid_y,
        )

    def _read_member(self, member: str) -> bytes:
        with zipfile.ZipFile(self._archive) as zf:
            return zf.read(member)

    def source_record(
        self, result: AdapterSuccess, *, doi: str, record_version: str
    ) -> SourceRecord:
        """The observed lineage root for a successful replay.

        `source_type` is set from the archive and member path, never from the columns: the source
        stores measured EDX and GP-predicted XPS in structurally identical files, so a column-based
        determination would conflate them (F-046).
        """
        return SourceRecord(
            doi=doi,
            record_version=record_version,
            source_filename=self._archive.name,
            source_sha256=digest(self._archive.read_bytes()),
            source_path=result.source_path,
            source_type="measured_lsv",
            parsing_version=ADAPTER_VERSION,
        )

    def synthetic_root(self, *, generator: str, generator_version: str, seed: int) -> SyntheticRoot:
        """The synthetic lineage root for a fixture-backed replay."""
        return SyntheticRoot(
            generator=generator,
            generator_version=generator_version,
            seed=seed,
            config_hash=digest(self._archive.read_bytes()),
        )
